services:
  postgres:
    image: postgres:18
    container_name: mini-pdm-postgres
    environment:
      POSTGRES_DB: mini_pdm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - mini-pdm-data:/var/lib/postgresql/data

volumes:
  mini-pdm-data:
